server:
  port: 7000
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5
spring:
  application:
    name: wops-configuration-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/goldengeek22/wops-config-store/
          default-label: master
          timeout: 10
          clone-on-start: true
          force-pull: true
